#:schema node_modules/wrangler/config-schema.json
name = "sublink-wo"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2ccdbd3bb9e44ecda5df9b2c7d7e7041" }
]

[assets]
directory = "./public"
